
title: "CHRIS' POSITIVE CODING"
url: 'https://ysm0622.github.io/blog'
baseurl: ''

title-kr: "크리스의 긍정코딩"
name: "Chris Yang"
disqus_shortname: "chrisy"

nav:
  -
    name: 'HOME'
    href: 'https://ysm0622.github.io/blog/'
  -
    name: 'PHOTO'
    href: 'https://ysm0622.github.io/photo/'
  -
    name: 'CV'
    href: 'https://ysm0622.github.io/cv/'
  -
    name: 'GITHUB'
    href: 'https://github.com/ysm0622/'
